# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-24 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.FileField(blank=True, upload_to='profile_images'),
        ),
    ]
